### ISSUE TITLE
discussion: shell completion and question on argument validation in Zig

### ISSUE THREAD

**Issue by matu3ba** [Gonzih/zigra#2]
I think that it could be useful, if Zig could provide portable shell completions at significant higher performance than the often clunky and slowish shell completions.

1. If one cares only mostly about size, a comptime-tri would be likely the best option: https://github.com/travisstaloch/comptime-trie.
2. If one cares about spelling mistakes, then applying on top levenstein distance or another method to find the likely word sounds best: https://github.com/nektro/zig-leven.

If one cares about argument validation, then there not many options other than arbitrary graph construction and resolving.
3. Can you think of typical use cases, where a framework could help to construct those things with marginal perf and low compilation time costs?

Would this fit into what zigra aims for or where do you think this would fit best?

**Comment by Gonzih** [comment]
Thats an interesting question, zigra aims at just providing command line tooling for zig applications. 
I would assume that completion indexing is something modern shells should handle in their own way or 3rd party tooling.
Fish shell for example generates completions out of man files, it would be possible to do the same based on output of `--help`. 

I would not tackle this as part of zigra past generating man pages or indexing hints for other shells. Even though current shell completions are slow and sluggish they are getting things done and are widely deployed, I don't see much point in trying to uproot existing tooling, integrating and leveraging what is out there is the way to go in my mind.

**Comment by matu3ba** [comment]
> I would assume that completion indexing is something modern shells should handle in their own way or 3rd party tooling.

Indexing on itself works okayish, but anything more complex becomes quickly a 1:n maintenance effort for each shell language and there is no way to add more advanced logic inside without making everything arbitrary complex.
I have looked into making a [grammar to derive such a completion program](https://gitlab.redox-os.org/AdminXVII/shellac-server) and [there are other failed attempts to solve this](https://github.com/openautocomplete/openautocomplete).

> uproot existing tooling

AFAIK each shell completer is a shell script written by third parties. What programs exist to autoderive those?

> I would not tackle this

Ah, kk. Then I'll play around with the idea abit more to see if it is feasible.

**Comment by Gonzih** [comment]
> AFAIK each shell completer is a shell script written by third parties. What programs exist to autoderive those?

I am not aware of anything that would address this problem, trying to having a standalone indexing tool would be an interesting idea. Another approach to this ofc would be something similar to github copilot but only for shell. Combined both approaches probably would produce best result.
